/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package EventManagementSystem;

import java.util.ArrayList;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableModel;

/**
 *
 * @author zahid
 */
public class EventDetails extends javax.swing.JFrame {

    /**
     * Creates new form OrderDetails
     */
    public EventDetails() {
        initComponents();
        fetchOrders();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        o_T = new javax.swing.JTable();
        jButton1 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel2.setBackground(new java.awt.Color(153, 153, 153));

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel1.setText("Order Details");

        o_T.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null}
            },
            new String [] {
                "Event", "Event ID", "Customer ID", "Waiters", "Chefs", "Photographers", "Chairs", "Tables", "Glasses", "Plates", "Date", "Time", "Lights", "Flowers", "Event Address", "Res_Name", "Res_ID", "Total"
            }
        ));
        o_T.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                o_TMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(o_T);
        if (o_T.getColumnModel().getColumnCount() > 0) {
            o_T.getColumnModel().getColumn(14).setPreferredWidth(150);
            o_T.getColumnModel().getColumn(15).setPreferredWidth(150);
        }

        jButton1.setText("Back");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jScrollPane1)
                        .addContainerGap())
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                        .addGap(0, 545, Short.MAX_VALUE)
                        .addComponent(jLabel1)
                        .addGap(476, 476, 476))))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jButton1)
                .addGap(487, 487, 487))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap(23, Short.MAX_VALUE)
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 344, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jButton1)
                .addGap(16, 16, 16))
        );

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void o_TMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_o_TMouseClicked
        // TODO add your handling code here:
          int n=o_T.getSelectedRow();
        TableModel Model = o_T.getModel();
        String orderid=Model.getValueAt(n,1).toString();
        new AssignEmployee(orderid).setVisible(true);
    }//GEN-LAST:event_o_TMouseClicked

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
         this.dispose();
        new AdminPanel().setVisible(true);
    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(EventDetails.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(EventDetails.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(EventDetails.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(EventDetails.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new EventDetails().setVisible(true);
            }
        });
    }
    
    public ArrayList<EventDetailsHolder> OrderList(){
        ArrayList<EventDetailsHolder> OrderList=new ArrayList<>();
        sqlConnect co = new sqlConnect();
        co.connectDB();
        String query;
      
        
        try {
           
            query="SELECT * FROM customerEvent ";
           
            co.resultSet = co.statement.executeQuery(query);
            EventDetailsHolder CO;

            while (co.resultSet.next()) {
                CO=new EventDetailsHolder(co.resultSet.getString("Event_type"),co.resultSet.getInt("Event_ID"),co.resultSet.getInt("C_ID"),co.resultSet.getInt("Waiters"),co.resultSet.getInt("Chefs"),co.resultSet.getInt("Photographer"),co.resultSet.getInt("Chairs"),co.resultSet.getInt("diningTable"),co.resultSet.getInt("Glasses"),co.resultSet.getInt("Plates"),co.resultSet.getString("Event_Date"),co.resultSet.getString("Event_Time"),co.resultSet.getInt("lights"),co.resultSet.getInt("flowers"),0,0,0,0,0,co.resultSet.getInt("TotalAmount"),co.resultSet.getString("Event_address"),co.resultSet.getString("Res_Name"),co.resultSet.getInt("Res_ID"));
                OrderList.add(CO);
                
              
            }
        } catch (Exception e) {
            e.printStackTrace();
        }

        return OrderList;
    }

    void fetchOrders() {

        ArrayList<EventDetailsHolder> list = OrderList();
        DefaultTableModel model = (DefaultTableModel) o_T.getModel();
        model.setRowCount(0);
        Object[] row = new Object[18];
        for (int i = 0; i < list.size(); i++) {
            row[0] = list.get(i).getEventType();
            row[1] = list.get(i).getEventID();
            row[2] = list.get(i).getCustomerID();
            row[3] = list.get(i).getWaiters();
            row[4] = list.get(i).getChef();
            row[5] = list.get(i).getPhotographers();
            row[6] = list.get(i).getChairs();
            row[7] = list.get(i).getTables();
            row[8] = list.get(i).getGlasses();
            row[9] = list.get(i).getPlates();
            row[10] = list.get(i).getDate();
            row[11] = list.get(i).getTime();
            row[12] = list.get(i).getFlowers();
            row[13] = list.get(i).getLights();
            row[14] = list.get(i).getAddress();
            row[15] = list.get(i).getRes_name();
            row[16] = list.get(i).getRes_id();
            row[17] = list.get(i).getTotalamount();
            model.addRow(row);

        }
        
    }


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable o_T;
    // End of variables declaration//GEN-END:variables
}
