package EventManagementSystem;

import java.sql.PreparedStatement;
import java.sql.Statement;
import java.util.ArrayList;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableModel;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */


public class RegisteredRestaurants extends javax.swing.JFrame {
    String resName,resLocation,resCapacity,resCost,query;
    
    
    public RegisteredRestaurants() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        searchTF = new javax.swing.JTextField();
        searchOptionsC = new javax.swing.JComboBox<>();
        jLabel2 = new javax.swing.JLabel();
        resIdTF = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        resCapacityTF = new javax.swing.JTextField();
        resNameTF = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        resCostTF = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        resLocTF = new javax.swing.JTextField();
        res_delete_btn = new rojerusan.RSButtonMetro();
        res_update_btn = new rojerusan.RSButtonMetro();
        jScrollPane1 = new javax.swing.JScrollPane();
        resT = new javax.swing.JTable();
        res_delete_btn1 = new rojerusan.RSButtonMetro();
        food = new rojerusan.RSButtonMetro();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));

        jPanel2.setBackground(new java.awt.Color(87, 101, 116));

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Registered Resturents");

        searchTF.setForeground(new java.awt.Color(109, 109, 109));
        searchTF.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                searchTFActionPerformed(evt);
            }
        });
        searchTF.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                searchTFKeyReleased(evt);
            }
        });

        searchOptionsC.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "ID", "Name", "Location", "Min Capacity", "Max Booking Cost" }));
        searchOptionsC.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                searchOptionsCMouseClicked(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                searchOptionsCMouseReleased(evt);
            }
        });
        searchOptionsC.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                searchOptionsCActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(searchOptionsC, javax.swing.GroupLayout.PREFERRED_SIZE, 146, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(66, 66, 66)
                .addComponent(searchTF, javax.swing.GroupLayout.PREFERRED_SIZE, 205, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(34, 34, 34))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(searchTF, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(searchOptionsC, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(28, Short.MAX_VALUE))
        );

        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel2.setText("Res_ID");

        resIdTF.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        jLabel3.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel3.setText("Booking Cost");

        resCapacityTF.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        resCapacityTF.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                resCapacityTFActionPerformed(evt);
            }
        });

        resNameTF.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        jLabel4.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel4.setText("Res_Name");

        jLabel5.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel5.setText("Capacity");

        resCostTF.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        jLabel6.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel6.setText("Location");

        resLocTF.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        res_delete_btn.setText("Delete");
        res_delete_btn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                res_delete_btnActionPerformed(evt);
            }
        });

        res_update_btn.setText("Update");
        res_update_btn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                res_update_btnActionPerformed(evt);
            }
        });

        resT.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Res_ID", "Res_Name", "Cost", "Location", "Capacity"
            }
        ));
        resT.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                resTMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(resT);

        res_delete_btn1.setText("Back");
        res_delete_btn1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                res_delete_btn1ActionPerformed(evt);
            }
        });

        food.setText("Food");
        food.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                foodActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(37, 37, 37)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel2)
                            .addComponent(jLabel3)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addComponent(resLocTF, javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(jPanel1Layout.createSequentialGroup()
                                    .addComponent(res_update_btn, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 56, Short.MAX_VALUE)
                                    .addComponent(res_delete_btn, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addComponent(resCapacityTF, javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(resNameTF, javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(resCostTF, javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(resIdTF, javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                        .addComponent(jLabel6, javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(jLabel5, javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(jLabel4, javax.swing.GroupLayout.Alignment.LEADING))
                                    .addGap(0, 0, Short.MAX_VALUE))))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 63, Short.MAX_VALUE)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 702, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(34, 34, 34))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(res_delete_btn1, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(56, 56, 56)
                        .addComponent(food, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(40, 40, 40)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(resIdTF, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(42, 42, 42)
                        .addComponent(jLabel4)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(resNameTF, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(42, 42, 42)
                        .addComponent(jLabel3)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(resCostTF, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(42, 42, 42)
                        .addComponent(jLabel6)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(resLocTF, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(42, 42, 42)
                        .addComponent(jLabel5)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(resCapacityTF, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 54, Short.MAX_VALUE)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(res_update_btn, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(res_delete_btn, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.TRAILING))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(res_delete_btn1, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(food, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(24, 24, 24))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void searchTFActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_searchTFActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_searchTFActionPerformed

    private void resCapacityTFActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_resCapacityTFActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_resCapacityTFActionPerformed

     public ArrayList<Restaurant> conventionCenterList(){
        ArrayList<Restaurant> conventionCenterList=new ArrayList<>();
        sqlConnect co = new sqlConnect();
        co.connectDB();
      
        
        try {
          
             
            co.resultSet = co.statement.executeQuery(query);
            Restaurant cc;

            while (co.resultSet.next()) {
                cc=new Restaurant(co.resultSet.getInt("Res_ID"),co.resultSet.getString("Res_Name"),co.resultSet.getString("Location")
                ,co.resultSet.getInt("Capacity"),co.resultSet.getInt("Booking_Cost"));
                conventionCenterList.add(cc);
                
              
            }
           
        } catch (Exception e) {
            e.printStackTrace();
        }

        return conventionCenterList;
    }
    public void show_convetionCenters()
    {
        ArrayList<Restaurant>list=conventionCenterList();
        DefaultTableModel model = (DefaultTableModel) resT.getModel();
        model.setRowCount(0);
        Object[] row =new Object[5];
        for(int i=0;i<list.size();i++)
        {
            row[0]=list.get(i).getRes_ID();
            row[1]=list.get(i).getRes_Name();
            row[2]=list.get(i).getBooking_Cost();
            row[3]=list.get(i).getLocation();
            row[4]=list.get(i).getCapacity();
            model.addRow(row);
            
        }
        
    }  
    private void res_update_btnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_res_update_btnActionPerformed
        // TODO add your handling code here:
       try {
            sqlConnect co = new sqlConnect();
            co.connectDB();
            Restaurant cc;
            if(resIdTF.getText().isEmpty())
            {
            if(resNameTF.getText().isEmpty() || resLocTF.getText().isEmpty() || resCapacityTF.getText().isEmpty() || resCostTF.getText().isEmpty())
            {
                JOptionPane.showMessageDialog(this,"Fill all the required fields!");
                return;
            }
            query="insert into Restaurant (Res_Name,Location,Capacity,Booking_Cost) values (?,?,?,?)";
            PreparedStatement pst=co.connection.prepareStatement(query);
            pst.setString(1, resNameTF.getText());
            pst.setString(2,resLocTF.getText());
            pst.setString(3,resCapacityTF.getText());
            pst.setString(4,resCostTF.getText());
            pst.executeUpdate();
            JOptionPane.showMessageDialog(this,"Restaurent added successfully!");
            query="Select *from Restaurant";
            show_convetionCenters();
            } 
            else 
            {   
            query="Select *from Restaurant where Res_ID = "+resIdTF.getText();
               
            co.resultSet = co.statement.executeQuery(query);
             while(co.resultSet.next()){
                  resName=co.resultSet.getString("Res_Name");
            resLocation=co.resultSet.getString("Location");
            resCapacity=co.resultSet.getInt("Capacity")+"";
            resCost=co.resultSet.getInt("Booking_Cost")+"";
             }
           
            
            if(!(resNameTF.getText().isEmpty()))
                resName=resNameTF.getText();
            if(!(resLocTF.getText().isEmpty()))
                resLocation=resLocTF.getText();
            if(!(resCapacityTF.getText().isEmpty()))
                resCapacity=resCapacityTF.getText();
            if(!(resCostTF.getText().isEmpty()))
                resCost=resCostTF.getText();
            
            query="Update Restaurant set Res_Name = '"+resName+"' ,Location = '"+resLocation+"' , Capacity = "+resCapacity+", Booking_Cost = "+resCost 
                    + " where Res_ID = "+resIdTF.getText();
            
            Statement st =co.connection.createStatement();
            st.executeUpdate(query);
          
          
            JOptionPane.showMessageDialog(this,"Restaurent Updated successfully!"); 
            query="Select *from Restaurant";
            show_convetionCenters();
            
            }
           
            }catch (Exception e) {
            e.printStackTrace();
            JOptionPane.showMessageDialog(this,"Failed to Update Restaurant");
        
       }   
       
    }//GEN-LAST:event_res_update_btnActionPerformed

    private void searchTFKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_searchTFKeyReleased
        // TODO add your handling code here:
        if(searchTF.getText().isEmpty())
            return;
        String so= searchOptionsC.getSelectedItem().toString();
        if(so.equals("ID") && searchTF.getText().charAt(searchTF.getText().length()-1)>='0' && searchTF.getText().charAt(searchTF.getText().length()-1)<='9')
        {  
          query="Select *from Restaurant where Res_ID = "+searchTF.getText();  
        }    
        else if(so.equals("Name"))
            query="Select *from Restaurant where Res_Name like '%"+searchTF.getText()+"%'";
        else if(so.equals("Min Capacity") && searchTF.getText().charAt(searchTF.getText().length()-1)>='0' && searchTF.getText().charAt(searchTF.getText().length()-1)<='9')
            query="Select *from Restaurant where Capacity >= "+searchTF.getText();
        else if(so.equals("Max Booking Cost") && searchTF.getText().charAt(searchTF.getText().length()-1)>='0' && searchTF.getText().charAt(searchTF.getText().length()-1)<='9')
            query="Select *from Restaurant where Booking_Cost <= "+searchTF.getText();
        else if(so.equals("Location"))
            query="Select *from Restaurant where Location like '%"+searchTF.getText()+"%'";
        else
            query="Select *from Restaurant";
        
        show_convetionCenters();
        
            
    }//GEN-LAST:event_searchTFKeyReleased

    private void searchOptionsCMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_searchOptionsCMouseClicked
        // TODO add your handling code here:
       query="Select *from Restaurant";
       show_convetionCenters();
    }//GEN-LAST:event_searchOptionsCMouseClicked

    private void searchOptionsCMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_searchOptionsCMouseReleased
        // TODO add your handling code here:
       
    }//GEN-LAST:event_searchOptionsCMouseReleased

    private void res_delete_btnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_res_delete_btnActionPerformed
        // TODO add your handling code here:
        try{
             sqlConnect co = new sqlConnect();
            co.connectDB();
             query="Delete from Restaurant where Res_ID = "+resIdTF.getText();
            
            Statement st =co.connection.createStatement();
            st.executeUpdate(query);
        }catch(Exception e){
            
        }
        
    }//GEN-LAST:event_res_delete_btnActionPerformed

    private void res_delete_btn1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_res_delete_btn1ActionPerformed
        // TODO add your handling code here:
        this.dispose();
        new AdminPanel().setVisible(true);
    }//GEN-LAST:event_res_delete_btn1ActionPerformed

    private void resTMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_resTMouseClicked
        // TODO add your handling code here:
        int n= resT.getSelectedRow();
        TableModel Model = resT.getModel();
        resIdTF.setText(Model.getValueAt(n,0).toString());
        resNameTF.setText(Model.getValueAt(n,1).toString());
        resCostTF.setText(Model.getValueAt(n,2).toString());
        resLocTF.setText(Model.getValueAt(n,3).toString());
        resCapacityTF.setText(Model.getValueAt(n,4).toString());
        
    }//GEN-LAST:event_resTMouseClicked

    private void foodActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_foodActionPerformed
        // TODO add your handling code here:
        this.dispose();
        new RestaurantFoodList(resIdTF.getText()).setVisible(true);
    }//GEN-LAST:event_foodActionPerformed

    private void searchOptionsCActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_searchOptionsCActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_searchOptionsCActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(RegisteredRestaurants.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(RegisteredRestaurants.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(RegisteredRestaurants.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(RegisteredRestaurants.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new RegisteredRestaurants().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private rojerusan.RSButtonMetro food;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField resCapacityTF;
    private javax.swing.JTextField resCostTF;
    private javax.swing.JTextField resIdTF;
    private javax.swing.JTextField resLocTF;
    private javax.swing.JTextField resNameTF;
    private javax.swing.JTable resT;
    private rojerusan.RSButtonMetro res_delete_btn;
    private rojerusan.RSButtonMetro res_delete_btn1;
    private rojerusan.RSButtonMetro res_update_btn;
    private javax.swing.JComboBox<String> searchOptionsC;
    private javax.swing.JTextField searchTF;
    // End of variables declaration//GEN-END:variables
}
